#!/usr/bin/env python3
"""Generate the design-token code from the Figma snapshot.

    python3 tools/gen_tokens.py

Reads  tools/tokens/a7_figma_tokens.json  (exported from Figma by tools/tokens/export_tokens.js)
Writes app-views/src/main/java/namvunhatle/r15/onboarding/core/ZenTokens.kt   (native drawing)
       app-views/src/main/res/values/zen_tokens.xml                      (XML layouts: colors, dimens)

A token keeps its Figma path: `Color/Background/Accent/Solid/Default` becomes
`Zen.Color.Background.Accent.Solid.Default` in Kotlin and `@color/zen_color_background_accent_solid_default` in XML.
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'tools/tokens/a7_figma_tokens.json')
KT = os.path.join(ROOT, 'app-views/src/main/java/namvunhatle/r15/onboarding/core/ZenTokens.kt')
XML = os.path.join(ROOT, 'app-views/src/main/res/values/zen_tokens.xml')

# Figma collection → Kotlin root object
ROOTS = {
    'Mode Colors (Semantic)': 'Zen', 'Component Colors (Theme)': 'Zen', 'Typography Configuration': 'Zen',
    'Spacing': 'Zen', 'Corner Radius': 'Zen', 'Emphasis Level': 'Zen', 'Component Size': 'Zen', 'Global Dimensions': 'Zen',
    '1 - Primitive: Typography': 'AdKit', '2 - Semantic: Scale': 'AdKit', '2 - Semantic: Typography': 'AdKit',
    '3 - Theming - Colors': 'AdKit',
    'Base Colors (Project)': 'Project',
    'AOSP': 'Aosp',
}
ROOT_DOC = {
    'Zen': '[Ring] ZEN Design System — the library the A7 screens are built with (read-only in Figma).',
    'AdKit': "The ad SDK kit behind 03 · Interstitial (SDK): another product's tokens, kept apart from ZEN.",
    'Project': 'Variables of the R15 file itself.',
    'Aosp': 'Material 3 kit (the status / navigation bars).',
}
# dimension tokens that make sense as XML dimens (dp)
DIMEN = re.compile(r'^(Spacing|Corner-Radius|Button/Size|Button/Spacing|Tag/|Badge/|Element-Size|zen-dm|Typography/(Font-Size|Line-Height)|gap/|size/|height/)')


def ident(seg):
    s = ''.join(p[:1].upper() + p[1:] for p in re.split(r'[-\s]+', seg) if p)
    return '_' + s if s[:1].isdigit() else s


def argb(c):
    r, g, b, a = (round(x * 255) for x in c)
    return (a << 24) | (r << 16) | (g << 8) | b


def main():
    data = json.load(open(SRC))
    tree = {}
    xml = []
    for v in data['variables']:
        root = ROOTS[v['collection']]
        path = v['name'].split('/')
        node = tree.setdefault(root, {})
        for seg in path[:-1]:
            node = node.setdefault(ident(seg), {})
            if not isinstance(node, dict):
                raise SystemExit(f"token path clash at {v['name']}")
        leaf = ident(path[-1])
        entry = (v['type'], v['value'], v['collection'], v['name'])
        old = node.get(leaf)
        if old is not None and (old[0], old[1]) != (entry[0], entry[1]):
            raise SystemExit(f"{v['name']}: {old[2]} = {old[1]} but {v['collection']} = {v['value']}")
        if old is None:
            node[leaf] = entry
            res = re.sub(r'[^a-z0-9]+', '_', (root + '_' + v['name']).lower()).strip('_')
            if v['type'] == 'COLOR':
                xml.append(f'    <color name="{res}">#{argb(v["value"]):08X}</color> <!-- {v["name"]} -->')
            elif v['type'] == 'FLOAT' and DIMEN.match(v['name']):
                xml.append(f'    <dimen name="{res}">{fmt(v["value"])}dp</dimen> <!-- {v["name"]} -->')

    out = [
        '// GENERATED by tools/gen_tokens.py from tools/tokens/a7_figma_tokens.json. Do not edit — re-export and regenerate.',
        '@file:Suppress("unused", "ObjectPropertyName")',
        '',
        'package namvunhatle.r15.onboarding.core',
        '',
        '/*',
        ' * Design tokens: the Figma variables bound in the A7 frames, under their Figma paths, with the values they resolve',
        ' * to there (ZEN modes Light · Global - Base 14 · Brand Emphasis - S1 · Base Colors Zen). Colors are ARGB ints;',
        ' * sizes are dp (or px, for letter spacing — divide by the font size for Android\'s em units).',
        ' * Values the design uses without a variable live in A7Visual.kt, not here.',
        ' */',
        '',
    ]
    for root in ['Zen', 'AdKit', 'Project', 'Aosp']:
        if root not in tree:
            continue
        out.append(f'/** {ROOT_DOC[root]} */')
        emit(out, root, tree[root], 0)
        out.append('')
    out += [
        '/** A Figma text style as a token triple: size, line height, letter spacing (dp / dp / px). */',
        'class TextToken(val size: Float, val line: Float, val tracking: Float)',
        '',
        '/** ZEN text styles, grouped from the Typography/Font-Size, Line-Height and Letter-Spacing tokens of the same name. */',
        'object ZenText {',
    ]
    ty = tree['Zen']['Typography']
    for name in sorted(ty['FontSize']):
        if name in ty.get('LineHeight', {}) and name in ty.get('LetterSpacing', {}):
            out.append(f'    val {name} = TextToken(Zen.Typography.FontSize.{name}, Zen.Typography.LineHeight.{name}, Zen.Typography.LetterSpacing.{name})')
    out.append('}')
    open(KT, 'w').write('\n'.join(out) + '\n')

    open(XML, 'w').write('<?xml version="1.0" encoding="utf-8"?>\n'
                         '<!-- GENERATED by tools/gen_tokens.py from tools/tokens/a7_figma_tokens.json. Do not edit. -->\n'
                         '<resources>\n' + '\n'.join(xml) + '\n</resources>\n')
    print(f'wrote {os.path.relpath(KT, ROOT)} and {os.path.relpath(XML, ROOT)} ({len(xml)} resources)')


def fmt(x):
    if isinstance(x, float) and not x.is_integer():
        return f'{x:.4f}'.rstrip('0')
    return str(int(x))


def emit(out, name, node, depth):
    pad = '    ' * depth
    out.append(f'{pad}object {name} {{')
    for key in sorted(node, key=lambda k: (isinstance(node[k], dict), k)):
        val = node[key]
        p = pad + '    '
        if isinstance(val, dict):
            emit(out, key, val, depth + 1)
            continue
        typ, v, coll, path = val
        if typ == 'COLOR':
            out.append(f'{p}/** {path} · #{argb(v):08X} */')
            out.append(f'{p}val {key} = 0x{argb(v):08X}.toInt()')
        elif typ == 'FLOAT':
            out.append(f'{p}const val {key} = {fmt(v)}f // {path}')
        elif typ == 'STRING':
            out.append(f'{p}const val {key} = "{v}" // {path}')
        else:
            raise SystemExit(f'{path}: unsupported type {typ}')
    out.append(f'{pad}}}')


if __name__ == '__main__':
    main()
