// GENERATED by tools/gen_tokens.py from tools/tokens/a7_figma_tokens.json. Do not edit — re-export and regenerate.
@file:Suppress("unused", "ObjectPropertyName")

package namvunhatle.r15.onboarding.core

/*
 * Design tokens: the Figma variables bound in the A7 frames, under their Figma paths, with the values they resolve
 * to there (ZEN modes Light · Global - Base 14 · Brand Emphasis - S1 · Base Colors Zen). Colors are ARGB ints;
 * sizes are dp (or px, for letter spacing — divide by the font size for Android's em units).
 * Values the design uses without a variable live in A7Visual.kt, not here.
 */

/** [Ring] ZEN Design System — the library the A7 screens are built with (read-only in Figma). */
object Zen {
    const val ZenDm40 = 40f // zen-dm-40
    const val ZenDm48 = 48f // zen-dm-48
    object Badge {
        object Size {
            const val XSmall = 16f // Badge/Size/XSmall
        }
        object Spacing {
            object XSmall {
                const val Gap = 2f // Badge/Spacing/XSmall/Gap
                const val HorizontalPadding = 2f // Badge/Spacing/XSmall/Horizontal-Padding
                const val TextWrapperPadding = 4f // Badge/Spacing/XSmall/Text-Wrapper-Padding
                const val VerticalPadding = 2f // Badge/Spacing/XSmall/Vertical-Padding
            }
        }
    }
    object Button {
        object Size {
            const val Large = 48f // Button/Size/Large
            const val XLarge = 56f // Button/Size/XLarge
        }
        object Spacing {
            object Large {
                const val Gap = 2f // Button/Spacing/Large/Gap
                const val HorizontalPadding = 16f // Button/Spacing/Large/Horizontal-Padding
                const val TextWrapperPadding = 4f // Button/Spacing/Large/Text-Wrapper-Padding
                const val VerticalPadding = 16f // Button/Spacing/Large/Vertical-Padding
            }
            object XLarge {
                const val Gap = 4f // Button/Spacing/XLarge/Gap
                const val HorizontalPadding = 16f // Button/Spacing/XLarge/Horizontal-Padding
                const val TextWrapperPadding = 4f // Button/Spacing/XLarge/Text-Wrapper-Padding
                const val VerticalPadding = 16f // Button/Spacing/XLarge/Vertical-Padding
            }
        }
    }
    object ButtonPrimary {
        object Background {
            /** Button-Primary/Background/Default · #FFBB4ABF */
            val Default = 0xFFBB4ABF.toInt()
        }
        object Content {
            /** Button-Primary/Content/Default · #FFFFFFFF */
            val Default = 0xFFFFFFFF.toInt()
        }
    }
    object ButtonTertiary {
        object Shadow {
            /** Button-Tertiary/Shadow/Default · #0A000000 */
            val Default = 0x0A000000.toInt()
        }
    }
    object Color {
        object Background {
            object Accent {
                object Gradient {
                    /** Color/Background/Accent/Gradient/Default-Left · #FFBB4ABF */
                    val DefaultLeft = 0xFFBB4ABF.toInt()
                    /** Color/Background/Accent/Gradient/Default-Right · #FF4752F0 */
                    val DefaultRight = 0xFF4752F0.toInt()
                }
                object Solid {
                    /** Color/Background/Accent/Solid/Default · #FFBB4ABF */
                    val Default = 0xFFBB4ABF.toInt()
                }
                object Subtle {
                    /** Color/Background/Accent/Subtle/Default · #16FF0298 */
                    val Default = 0x16FF0298.toInt()
                }
            }
            object Active {
                object Accent {
                    /** Color/Background/Active/Accent/Solid · #FFBB4ABF */
                    val Solid = 0xFFBB4ABF.toInt()
                }
            }
            object Neutral {
                object Flat {
                    /** Color/Background/Neutral/Flat/Default · #00FFFFFF */
                    val Default = 0x00FFFFFF.toInt()
                }
                object Subtle {
                    /** Color/Background/Neutral/Subtle/Default · #10010101 */
                    val Default = 0x10010101.toInt()
                }
            }
            object Support {
                object Blue {
                    /** Color/Background/Support/Blue/Deep · #FF002B56 */
                    val Deep = 0xFF002B56.toInt()
                    /** Color/Background/Support/Blue/Solid · #FF0A85FF */
                    val Solid = 0xFF0A85FF.toInt()
                }
                object Bronze {
                    /** Color/Background/Support/Bronze/Deep · #FF571400 */
                    val Deep = 0xFF571400.toInt()
                }
                object Crimson {
                    /** Color/Background/Support/Crimson/Deep · #FF590023 */
                    val Deep = 0xFF590023.toInt()
                    /** Color/Background/Support/Crimson/Solid · #FFE94E75 */
                    val Solid = 0xFFE94E75.toInt()
                }
                object Cyan {
                    /** Color/Background/Support/Cyan/Solid · #FF10AEDA */
                    val Solid = 0xFF10AEDA.toInt()
                }
                object Golden {
                    /** Color/Background/Support/Golden/Solid · #FFC99A2C */
                    val Solid = 0xFFC99A2C.toInt()
                }
                object Green {
                    /** Color/Background/Support/Green/Solid · #FF3FAB53 */
                    val Solid = 0xFF3FAB53.toInt()
                }
                object Indigo {
                    /** Color/Background/Support/Indigo/Deep · #FF0F0075 */
                    val Deep = 0xFF0F0075.toInt()
                }
                object Neutral {
                    /** Color/Background/Support/Neutral/Deep · #FF0D0D0D */
                    val Deep = 0xFF0D0D0D.toInt()
                    /** Color/Background/Support/Neutral/Pale · #08050505 */
                    val Pale = 0x08050505.toInt()
                    /** Color/Background/Support/Neutral/Subtle · #10010101 */
                    val Subtle = 0x10010101.toInt()
                }
                object Orange {
                    /** Color/Background/Support/Orange/Solid · #FFED8002 */
                    val Solid = 0xFFED8002.toInt()
                }
                object Pink {
                    /** Color/Background/Support/Pink/Solid · #FFE854B2 */
                    val Solid = 0xFFE854B2.toInt()
                }
                object Plum {
                    /** Color/Background/Support/Plum/Deep · #FF46004E */
                    val Deep = 0xFF46004E.toInt()
                }
                object Teal {
                    /** Color/Background/Support/Teal/Deep · #FF003932 */
                    val Deep = 0xFF003932.toInt()
                    /** Color/Background/Support/Teal/Solid · #FF02B19C */
                    val Solid = 0xFF02B19C.toInt()
                }
                object Violet {
                    /** Color/Background/Support/Violet/Deep · #FF27006E */
                    val Deep = 0xFF27006E.toInt()
                    /** Color/Background/Support/Violet/Solid · #FF7755E7 */
                    val Solid = 0xFF7755E7.toInt()
                }
                object Yellow {
                    /** Color/Background/Support/Yellow/Solid · #FFFFBA1A */
                    val Solid = 0xFFFFBA1A.toInt()
                }
            }
            object Warning {
                object Solid {
                    /** Color/Background/Warning/Solid/Default · #FFFFBA1A */
                    val Default = 0xFFFFBA1A.toInt()
                }
            }
            object WhiteSolid {
                /** Color/Background/White-Solid/Default · #FFFFFFFF */
                val Default = 0xFFFFFFFF.toInt()
            }
        }
        object Border {
            object Accent {
                object Solid {
                    /** Color/Border/Accent/Solid/Default · #FFBB4ABF */
                    val Default = 0xFFBB4ABF.toInt()
                }
            }
            object Neutral {
                object Pale {
                    /** Color/Border/Neutral/Pale/Default · #10010101 */
                    val Default = 0x10010101.toInt()
                }
            }
            object Overlay {
                object Pale {
                    /** Color/Border/Overlay/Pale/Default · #11FCFCFC */
                    val Default = 0x11FCFCFC.toInt()
                }
                object Subtle {
                    /** Color/Border/Overlay/Subtle/Default · #1AFFFFFF */
                    val Default = 0x1AFFFFFF.toInt()
                }
            }
        }
        object Content {
            /** Color/Content/On-Brights · #DB000000 */
            val OnBrights = 0xDB000000.toInt()
            /** Color/Content/On-Colors · #FFFFFFFF */
            val OnColors = 0xFFFFFFFF.toInt()
            object Accent {
                /** Color/Content/Accent/Base · #FF781A7F */
                val Base = 0xFF781A7F.toInt()
            }
            object Neutral {
                /** Color/Content/Neutral/Strongest · #FF0D0D0D */
                val Strongest = 0xFF0D0D0D.toInt()
            }
            object OnAccent {
                /** Color/Content/On-Accent/Default · #FFFFFFFF */
                val Default = 0xFFFFFFFF.toInt()
            }
            object OnDarkOverlay {
                /** Color/Content/On-Dark-Overlay/Base · #CBFFFFFF */
                val Base = 0xCBFFFFFF.toInt()
                /** Color/Content/On-Dark-Overlay/Disabled · #39FFFFFF */
                val Disabled = 0x39FFFFFF.toInt()
                /** Color/Content/On-Dark-Overlay/Light · #5CFFFFFF */
                val Light = 0x5CFFFFFF.toInt()
                /** Color/Content/On-Dark-Overlay/Strongest · #F4FFFFFF */
                val Strongest = 0xF4FFFFFF.toInt()
            }
            object OnWhiteOverlay {
                /** Color/Content/On-White-Overlay/Base · #A3000000 */
                val Base = 0xA3000000.toInt()
                /** Color/Content/On-White-Overlay/Strongest · #F2000000 */
                val Strongest = 0xF2000000.toInt()
            }
        }
        object Shadow {
            object Neutral {
                /** Color/Shadow/Neutral/Light · #0A000000 */
                val Light = 0x0A000000.toInt()
            }
        }
    }
    object CornerRadius {
        const val Base = 12f // Corner-Radius/Base
        const val Giant = 32f // Corner-Radius/Giant
        const val Large = 16f // Corner-Radius/Large
        const val Rounded = 1000f // Corner-Radius/Rounded
        const val Small = 8f // Corner-Radius/Small
        const val XLarge = 20f // Corner-Radius/XLarge
        const val _2XLarge = 24f // Corner-Radius/2XLarge
        object Action {
            const val Large = 1000f // Corner-Radius/Action/Large
            const val XLarge = 1000f // Corner-Radius/Action/XLarge
        }
    }
    object ElementSize {
        object Popular {
            const val Base = 20f // Element-Size/Popular/Base
            const val Large = 28f // Element-Size/Popular/Large
            const val XSmall = 12f // Element-Size/Popular/XSmall
        }
    }
    object Emphasis {
        object FontWeight {
            const val Bold = 600f // Emphasis/Font-Weight/Bold
            const val Medium = 500f // Emphasis/Font-Weight/Medium
            const val Regular = 400f // Emphasis/Font-Weight/Regular
        }
    }
    object Spacing {
        object Gap {
            const val Large = 24f // Spacing/Gap/Large
            const val Medium = 16f // Spacing/Gap/Medium
            const val Small = 12f // Spacing/Gap/Small
            const val XLarge = 32f // Spacing/Gap/XLarge
            const val XSmall = 8f // Spacing/Gap/XSmall
            const val _2XSmall = 4f // Spacing/Gap/2XSmall
        }
        object Padding {
            const val Large = 20f // Spacing/Padding/Large
            const val Medium = 16f // Spacing/Padding/Medium
            const val Small = 12f // Spacing/Padding/Small
            const val XLarge = 24f // Spacing/Padding/XLarge
            const val XSmall = 8f // Spacing/Padding/XSmall
            const val _2XSmall = 4f // Spacing/Padding/2XSmall
            const val _3XSmall = 2f // Spacing/Padding/3XSmall
        }
    }
    object Tag {
        object Background {
            /** Tag/Background/Default · #FFFCFCFC */
            val Default = 0xFFFCFCFC.toInt()
        }
        object Border {
            /** Tag/Border/Default · #1D010101 */
            val Default = 0x1D010101.toInt()
        }
        object Size {
            const val Medium = 28f // Tag/Size/Medium
        }
        object Spacing {
            object Medium {
                const val Gap = 2f // Tag/Spacing/Medium/Gap
                const val HorizontalPadding = 6f // Tag/Spacing/Medium/Horizontal-Padding
                const val TextWrapperPadding = 4f // Tag/Spacing/Medium/Text-Wrapper-Padding
                const val VerticalPadding = 4f // Tag/Spacing/Medium/Vertical-Padding
            }
        }
    }
    object Typography {
        object FontFamily {
            const val Button = "Be Vietnam Pro" // Typography/Font-Family/Button
            const val Display = "Be Vietnam Pro" // Typography/Font-Family/Display
            const val Heading = "Be Vietnam Pro" // Typography/Font-Family/Heading
            const val Sans = "Be Vietnam Pro" // Typography/Font-Family/Sans
        }
        object FontSize {
            const val BodyBase = 14f // Typography/Font-Size/Body-Base
            const val BodySmall = 12f // Typography/Font-Size/Body-Small
            const val ButtonLabelL = 14f // Typography/Font-Size/Button-Label-L
            const val ButtonLabelXL = 16f // Typography/Font-Size/Button-Label-XL
            const val Caption = 10f // Typography/Font-Size/Caption
            const val Display1 = 52f // Typography/Font-Size/Display-1
            const val Heading1 = 32f // Typography/Font-Size/Heading-1
            const val Heading2 = 28f // Typography/Font-Size/Heading-2
            const val Heading3 = 24f // Typography/Font-Size/Heading-3
            const val Heading4 = 20f // Typography/Font-Size/Heading-4
        }
        object LetterSpacing {
            const val ALLCAPSM = 0f // Typography/Letter-Spacing/ALL-CAPS-M
            const val BodyBase = -0.32f // Typography/Letter-Spacing/Body-Base
            const val BodySmall = -0.28f // Typography/Letter-Spacing/Body-Small
            const val ButtonLabelL = -0.32f // Typography/Letter-Spacing/Button-Label-L
            const val ButtonLabelXL = -0.4f // Typography/Letter-Spacing/Button-Label-XL
            const val Caption = -0.12f // Typography/Letter-Spacing/Caption
            const val Display1 = -3f // Typography/Letter-Spacing/Display-1
            const val Heading1 = -1.44f // Typography/Letter-Spacing/Heading-1
            const val Heading2 = -0.96f // Typography/Letter-Spacing/Heading-2
            const val Heading3 = -0.84f // Typography/Letter-Spacing/Heading-3
            const val Heading4 = -0.72f // Typography/Letter-Spacing/Heading-4
        }
        object LineHeight {
            const val BodyBase = 20f // Typography/Line-Height/Body-Base
            const val BodySmall = 16f // Typography/Line-Height/Body-Small
            const val ButtonLabelL = 20f // Typography/Line-Height/Button-Label-L
            const val ButtonLabelXL = 24f // Typography/Line-Height/Button-Label-XL
            const val Caption = 16f // Typography/Line-Height/Caption
            const val Display1 = 60f // Typography/Line-Height/Display-1
            const val Heading1 = 40f // Typography/Line-Height/Heading-1
            const val Heading2 = 36f // Typography/Line-Height/Heading-2
            const val Heading3 = 32f // Typography/Line-Height/Heading-3
            const val Heading4 = 28f // Typography/Line-Height/Heading-4
        }
    }
}

/** The ad SDK kit behind 03 · Interstitial (SDK): another product's tokens, kept apart from ZEN. */
object AdKit {
    object Background {
        /** background/bg-overlay · #2BFFFFFF */
        val BgOverlay = 0x2BFFFFFF.toInt()
    }
    object Content {
        /** content/ct-emphasis · #FFF8FAFC */
        val CtEmphasis = 0xFFF8FAFC.toInt()
        /** content/ct-medium · #FFE2E8F0 */
        val CtMedium = 0xFFE2E8F0.toInt()
    }
    object Family {
        const val Content = "Mona Sans" // family/content
    }
    object Gap {
        object Lg {
            const val Lg4 = 48f // gap/lg/lg-4
        }
        object Md {
            const val Md2 = 16f // gap/md/md-2
        }
        object Sm {
            const val Sm3 = 6f // gap/sm/sm-3
            const val Sm4 = 8f // gap/sm/sm-4
        }
    }
    object Height {
        const val HeightLabelMd = 16f // height/height-label-md
    }
    object Size {
        const val SizeLabelMd = 12f // size/size-label-md
    }
    object Weight {
        const val Default = 500f // weight/default
    }
}

/** Variables of the R15 file itself. */
object Project {
    /** White · #FFFFFFFF */
    val White = 0xFFFFFFFF.toInt()
}

/** Material 3 kit (the status / navigation bars). */
object Aosp {
    object Schemes {
        /** Schemes/On Surface · #FF171D1B */
        val OnSurface = 0xFF171D1B.toInt()
    }
}

/** A Figma text style as a token triple: size, line height, letter spacing (dp / dp / px). */
class TextToken(val size: Float, val line: Float, val tracking: Float)

/** ZEN text styles, grouped from the Typography/Font-Size, Line-Height and Letter-Spacing tokens of the same name. */
object ZenText {
    val BodyBase = TextToken(Zen.Typography.FontSize.BodyBase, Zen.Typography.LineHeight.BodyBase, Zen.Typography.LetterSpacing.BodyBase)
    val BodySmall = TextToken(Zen.Typography.FontSize.BodySmall, Zen.Typography.LineHeight.BodySmall, Zen.Typography.LetterSpacing.BodySmall)
    val ButtonLabelL = TextToken(Zen.Typography.FontSize.ButtonLabelL, Zen.Typography.LineHeight.ButtonLabelL, Zen.Typography.LetterSpacing.ButtonLabelL)
    val ButtonLabelXL = TextToken(Zen.Typography.FontSize.ButtonLabelXL, Zen.Typography.LineHeight.ButtonLabelXL, Zen.Typography.LetterSpacing.ButtonLabelXL)
    val Caption = TextToken(Zen.Typography.FontSize.Caption, Zen.Typography.LineHeight.Caption, Zen.Typography.LetterSpacing.Caption)
    val Display1 = TextToken(Zen.Typography.FontSize.Display1, Zen.Typography.LineHeight.Display1, Zen.Typography.LetterSpacing.Display1)
    val Heading1 = TextToken(Zen.Typography.FontSize.Heading1, Zen.Typography.LineHeight.Heading1, Zen.Typography.LetterSpacing.Heading1)
    val Heading2 = TextToken(Zen.Typography.FontSize.Heading2, Zen.Typography.LineHeight.Heading2, Zen.Typography.LetterSpacing.Heading2)
    val Heading3 = TextToken(Zen.Typography.FontSize.Heading3, Zen.Typography.LineHeight.Heading3, Zen.Typography.LetterSpacing.Heading3)
    val Heading4 = TextToken(Zen.Typography.FontSize.Heading4, Zen.Typography.LineHeight.Heading4, Zen.Typography.LetterSpacing.Heading4)
}
